apiVersion: v1
kind: ConfigMap
metadata:
  name: op-node-base-env
data:
  OP_NODE_L1_ETH_RPC: <your L1 ETH RPC here>
  OP_NODE_RPC_ADDR: 0.0.0.0
  OP_NODE_RPC_PORT: "9545"
  OP_NODE_P2P_LISTEN_IP: 0.0.0.0
  OP_NODE_P2P_LISTEN_TCP_PORT: "9003"
  OP_NODE_P2P_LISTEN_UDP_PORT: "9003"
  OP_NODE_P2P_PRIV_PATH: /etc/op-node/p2p-node-key.txt
  OP_NODE_P2P_ADVERTISE_TCP: "9003"
  OP_NODE_P2P_ADVERTISE_UDP: "9003"
  OP_NODE_P2P_PEERSTORE_PATH: /p2p/peerstore
  OP_NODE_P2P_DISCOVERY_PATH: /p2p/discovery
  OP_NODE_METRICS_ENABLED: "true"
  OP_NODE_METRICS_ADDR: 0.0.0.0
  OP_NODE_METRICS_PORT: "7300"
  OP_NODE_L2_ENGINE_AUTH: /etc/op-node/jwt-secret.txt
  OP_NODE_SEQUENCER_L1_CONFS: "4"
  OP_NODE_VERIFIER_L1_CONFS: "4"
  OP_NODE_LOG_FORMAT: json
  OP_NODE_LOG_LEVEL: info
  OP_NODE_PPROF_ENABLED: "true"
  OP_NODE_PPROF_PORT: "6666"
  OP_NODE_PPROF_ADDR: 0.0.0.0
  OP_NODE_HEARTBEAT_MONIKER: op-bedrock
  OP_NODE_HEARTBEAT_ENABLED: "true"